import React from 'react';
import Navigation from './Navigation';
import TodoList from './TodoList';
import './index.css'; // This is for Tailwind CSS (generated by Create React App)

function App() {
  return (
    <div>
      <Navigation />
      <TodoList />
    </div>
  );
}

export default App;
